version: '3'
services:
  eureka:
    image: swarm.inf.uniroma3.it:5000/Eureka-server-img-9006
    deploy:
      placement:
        constraints: [node.role == manager]
  R1:
    image: swarm.inf.uniroma3.it:5000/R1-img-9006
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 1    
  R2:
    image: swarm.inf.uniroma3.it:5000/R2-img-9006
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 1       
  RomaTre:
    image: swarm.inf.uniroma3.it:5000/RomaTre-img-9006
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 2    
  zuul:
    image: swarm.inf.uniroma3.it:5000/Zuul-server-img-9006 
    depends_on:
    - "eureka"
    ports:
    - "9006:8080"