version: '3'
services:
  eureka:
    image: swarm.inf.uniroma3.it:5000/eureka-img-9006
#    ports:
#    - "8761:8761"
    deploy:
      placement:
        constraints: [node.role == manager]
  r1:
    image: swarm.inf.uniroma3.it:5000/r1-img-9006
#    ports:
#    - "8081:8080"
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 1
  r2:
    image: swarm.inf.uniroma3.it:5000/r2-img-9006
#    ports:
#    - "8082:8080"
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 1
  romatre:
    image: swarm.inf.uniroma3.it:5000/romatre-img-9006
#    ports:
#    - "8080:8080"
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 2
  zuul:
    image: swarm.inf.uniroma3.it:5000/zuul-img-9006
    ports:
    - "9006:8080"
    depends_on:
    - "eureka"




