# application.yml 
--- 
spring: 
  application: 
    name: zuul
server:
  port: 8080
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 10